# Generated by Django 3.1.1 on 2020-09-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MvmExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='sielte_export')),
            ],
        ),
        migrations.CreateModel(
            name='SielteExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='sielte_export')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedfilemvm',
            name='obj',
            field=models.ForeignKey(default='OBJ_MISSING', on_delete=django.db.models.deletion.CASCADE, to='tickets.mvmimport'),
        ),
        migrations.AlterField(
            model_name='uploadedfilesielte',
            name='obj',
            field=models.ForeignKey(default='OBJ_MISSING', on_delete=django.db.models.deletion.CASCADE, to='tickets.sielteimport'),
        ),
    ]
