# Generated by Django 3.1.1 on 2020-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200923_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvmimport',
            old_name='colonna',
            new_name='colonna_cp_colonna',
        ),
        migrations.RenameField(
            model_name='mvmimport',
            old_name='rl',
            new_name='rl_cp_rl',
        ),
        migrations.RemoveField(
            model_name='mvmimport',
            name='cp_col',
        ),
        migrations.RemoveField(
            model_name='mvmimport',
            name='cp_rl',
        ),
        migrations.AlterField(
            model_name='mvmexport',
            name='file',
            field=models.FileField(upload_to='mvm_export'),
        ),
    ]
