# Generated by Django 3.2.2 on 2021-06-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210618_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvmimport',
            name='annotazi',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='appu_old',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='building',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='campo001',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='campo002',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='carat_wr',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='causobbi',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='clli_roe',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='cod_modem',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='cod_wrid',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codfonte',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codi_aoa',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codi_aor',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codi_arm',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codi_box',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codi_dtu',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codi_isp',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codiassi',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codicant',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codicaus',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codicavo',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codicent',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codicewr',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codiclie',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codicont',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codidipe',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codiimpi',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codinetw',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codiolia',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codiordi',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codirep2',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codirep3',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codirepa',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codisede',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='codisqua',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='coditipo',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='colosla1',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='contexto',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='data_dad',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='dati_olo',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='decina',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='des_cogn',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='des_indi',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='des_loca',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='des_prov',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desc_aoa',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desc_aor',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desc_isp',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desc_job',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desc_olo',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desc_pal',
            field=models.CharField(blank=True, choices=[('ADSL', 'ADSL'), ('FONIA', 'FONIA')], default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='descassi',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desccant',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desccent',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='descdipe',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desclavb',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desclavo',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='descomme',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='descsqua',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='descstat',
            field=models.CharField(blank=True, choices=[('ACQUISTE', 'ACQUISTE'), ('CHIUSE', 'CHIUSE')], default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='desctipo',
            field=models.CharField(blank=True, choices=[('NUOVI IMPIANTI ADSL', 'NUOVI IMPIANTI ADSL'), ('NUOVI IMPIANTI FONIA', 'NUOVI IMPIANTI FONIA')], default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='diagnosi',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='dipesuba',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='fasc_dad',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='flussogc',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='idwrprec',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='indimail',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='keylavw5',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='noteimpr',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='numepref',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='numetele',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='operazio',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='path_pop',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='pos_dely',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='prevriso',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='prognazi',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='recacli1',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='recaclie',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='reclamoc',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='recolock',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='ref_cogn',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='ref_nome',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='repa_usc',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='response',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='ricez_dt',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='ripecavo',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='ripesqua',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='ripetele',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='risvsqua',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='risvtele',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='seriale_modem',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='sla16_40',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='sla16_70',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='splitsec',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='systunic',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='tipoback',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='tipofore',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='tipologia_modem',
            field=models.CharField(blank=True, choices=[('MODEM 100', 'MODEM 100'), ('MODEM 200', 'MODEM 200'), ('FRITZ BOX 7590', 'FRITZ BOX 7590'), ('FRITZ BOX 6890', 'FRITZ BOX 6890'), ('TIM BOX', 'TIM BOX'), ('MODEM PLUS', 'MODEM PLUS')], default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='tipoprec',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mvmimport',
            name='zonacent',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
