# Generated by Django 3.2.2 on 2021-08-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210618_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sielteimport',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('SOSPESO', 'SOSPESO'), ('ANNULLATO', 'ANNULLATO'), ('DA LAVORARE', 'DA LAVORARE')], max_length=256, null=True, verbose_name='Stato lavoro'),
        ),
    ]
