# Generated by Django 3.2.2 on 2021-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210616_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='end_date',
            field=models.DateField(blank=True, default='17/06/2021', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='start_date',
            field=models.DateField(blank=True, default='17/06/2021', max_length=256, null=True),
        ),
    ]
