# Generated by Django 3.2.2 on 2021-06-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210617_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='end_date',
            field=models.DateField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='start_date',
            field=models.DateField(blank=True, max_length=256, null=True),
        ),
    ]
