# Generated by Django 3.2.2 on 2021-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='plain_text',
            field=models.TextField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
